eastwood/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.index_view, name="home"),
]

eastwood/employees/urls.py
from django.urls import path
from . import views

app_name = "employees"

urlpatterns = [
    path('', views.EmployeesListView.as_view(), name="list"),
    path('actual/', views.EmployeesRecentView.as_view(), name="actual"),
    path('dict/', views.EmployeeDictionaryView.as_view(), name="dict"),
    path('dict/<int:part>', views.EmployeeDictionaryView.as_view(), name="dict_part"),
    path('dept/<int:dept>', views.EmployeesDeptView.as_view(), name="dept"),
    path('<int:pk>', views.EmployeeDetail.as_view(), name="detail"),
]

eastwood/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('eastwood.core.urls')),
    path('employees/', include('eastwood.employees.urls')),
    path('admin/', admin.site.urls),
]

eastwood/core/models.py
from django.db import models

eastwood/employees/models.py
from django.core.validators import RegexValidator
from django.db import models


class Department(models.Model):

    name = models.CharField(max_length=100, null=False, blank=False, default="")

    def __str__(self):
        return f"{self.name}"


class Employee(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, default="")
    patronymic = models.CharField(max_length=50, null=True, blank=True, default="", help_text="Leave blank if none")
    surname = models.CharField(max_length=50, null=False, blank=False, default="")
    birth_date = models.DateField(blank=False, null=True)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        validators=[RegexValidator(regex=r'^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$')],
        help_text="Cell phone number is recommended"
    )
    started_work = models.DateField(blank=False, null=True)
    ended_work = models.DateField(blank=True, null=True)
    position = models.CharField(max_length=100, null=False, blank=False, default="")
    dept = models.ForeignKey(Department, on_delete=models.CASCADE, default="")

    def __str__(self):
        if self.patronymic:
            return f"{self.name} {self.patronymic} {self.surname}"
        else:
            return f"{self.name} {self.surname}"

eastwood/core/views.py
from django.shortcuts import render


def index_view(request):
    return render(request, 'home.html')

eastwood/employees/views.py
from typing import List

from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Employee, Department
from itertools import groupby
from operator import itemgetter


# Dictionary main logic


#
def chunks(items: List[Employee]):
    """
     Logic was taken from here  https://qna.habr.com/q/373740
    Split by groups for the first letter of surname.

    :param items: list of all employees sorted by surname
    :return: generator
    """
    dict_name = []
    for x in items:
        dict_name.append(f"{x.surname} {x.name}#{x.id}")  # Appending an ID simplifies search in view logic
    for letter, names in groupby(sorted(dict_name), key=itemgetter(0)):
        yield list(names)


#
def reshape(items, min_len, max_len):
    """
     Merging the groups with size less then min_len to a size less or equal then max_len
    :param items:   list of names (+id)
    :param min_len: minimal size of each group
    :param max_len: maximal size of each group
    :return: generator
    """
    buffer = []
    for item in items:
        if len(buffer) >= max_len:
            yield sorted(buffer)
            buffer = []
        if len(item) <= min_len:
            buffer += item
        else:
            yield item
    yield sorted(buffer)


def dictionarize(sort_orders: List[Employee]):
    """
    Returns a formatted dict.

    """
    groups_list = reshape(chunks(sort_orders), len(sort_orders) // 3, len(sort_orders) // 5)
    result = {'{}-{}'.format(item[0][0], item[-1][0]): item for item in groups_list}
    return result


# --------------------------------------------------

class EmployeesListView(ListView):
    """
        Default list with all employees.
    """
    model = Employee
    context_object_name = "all_employees"
    paginate_by = 3
    paginate_orphans = 1
    ordering = ['id']


class EmployeesDeptView(ListView):
    """
       Sorted by department view.
    """
    template_name = "employees/employee_dept.html"
    context_object_name = "dept_employees"
    paginate_by = 3
    paginate_orphans = 1
    ordering = ['id']
    dept = None

    def get_queryset(self):
        """

        :return: queryset where employees are belong to required department
        """
        self.dept = get_object_or_404(Department, id=self.kwargs['dept'])
        return Employee.objects.filter(dept=self.dept)

    def get_context_data(self, **kwargs):
        """
            returns context data with dept parameter
        """
        context = super(EmployeesDeptView, self).get_context_data(**kwargs)
        context['dept'] = self.dept
        return context


class EmployeesRecentView(ListView):
    """
        list with employees who is still working
    """
    template_name = "employees/employee_actual.html"
    context_object_name = "recent_employees"
    paginate_by = 3
    paginate_orphans = 5
    ordering = ['id']

    def get_queryset(self):
        """
        :return: queryset where model field ended_work is equal to empty.
        """
        result = Employee.objects.exclude(ended_work__isnull=False)
        return result


class EmployeeDetail(DetailView):
    model = Employee
    context_object_name = "employee"
    queryset = Employee.objects.all()


class EmployeeDictionaryView(ListView):
    """
        Dictionary view.

        Accepts 0 or 1 parameter ("part"). If 0 displays a list of hyperlinks
        that represents the first letter of each employee surname in list.
    """
    template_name = "employees/employee_dict.html"
    context_object_name = "dict"
    dictionary = dictionarize(Employee.objects.all().order_by('surname'))
    paginate_by = 3
    paginate_orphans = 5

    def get_context_data(self, **kwargs):
        """
        :return: display a group of links
        """
        context = super(EmployeeDictionaryView, self).get_context_data(**kwargs)
        keys_dict = {}
        for counter, key in enumerate(self.dictionary.keys()):
            keys_dict[counter] = key
        context["keys"] = keys_dict
        if self.kwargs:
            context["selected_key"] = list(self.dictionary.keys())[self.kwargs['part']]
        print(context)
        return context

    def get_queryset(self):
        """
        :return: a queryset that contains all the employees which surname' first letter
                are in range of the current link
        """
        queryset = []
        if self.kwargs:
            vals = list(self.dictionary.values())
            for item in vals[self.kwargs['part']]:
                id = item.split("#")[1]
                queryset.append(get_object_or_404(Employee, id=id))
        return queryset

eastwood/templates/base.html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<title>Eastwood test task</title>
{% load static %}
    <link rel="stylesheet" href="{% static 'footer.css' %}">
</head>
<body>
    {% include "nav.html" %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-10">
        {% block content %}
        {% endblock %}
            </div>
        </div>
    </div>

   <footer class="footer">
      <div class="container ">
        <span class="text-muted">{%block footer%}  {% endblock %} Powered on Python without SPAM</span>
      </div>
 </footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

eastwood/templates/employees/employee_actual.html
{% extends 'base.html' %}

{% block content %}

<h2>All recent employees</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Full name</th>
      <th scope="col">Position</th>
      <th scope="col">Worked since</th>
    </tr>
  </thead>
  <tbody>

  {% for employee in recent_employees %}

    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>
        <a href="{% url 'employees:detail' employee.id %}">
          {{ employee.name }}
           {% if  employee.patronymic %}
                {{ employee.patronymic }}
          {% endif %}
          {{ employee.surname }}
        </a>
      </td>
      <td>
          {{ employee.position }}, <a href="{% url 'employees:dept' employee.dept.id %}"> {{ employee.dept }}</a>
      </td>
      <td>
        {{ employee.started_work }}
      </td>
    </tr>

  {% endfor %}

  </tbody>
</table>

{% include 'pagination.html' %}

{% endblock %}

eastwood/templates/employees/employee_dept.html
{% extends 'base.html' %}

{% block content %}
<h2>All employees from {{ dept.name }}</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Full name</th>
      <th scope="col">Position</th>
      <th scope="col">Worked time</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in dept_employees %}

      <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>
        <a href="{% url 'employees:detail' employee.id %}">
          {{ employee.name }}
           {% if  employee.patronymic %}
                {{ employee.patronymic }}
          {% endif %}
          {{ employee.surname }}
        </a>
      </td>
      <td>{{ employee.position }}</td>
      <td>
        {{ employee.started_work }}
            {% if employee.ended_work %}
                {{ employee.ended_work }}
            {% endif %}
      </td>
      </tr>

    {% endfor %}
  </tbody>
</table>


{% include 'pagination.html' %}

{% endblock %}

eastwood/templates/employees/employee_detail.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-borderless table-sm mt-20 text-center">
  <tbody>
    <tr>
        <th scope="row" colspan="2">Detail employee view </th>
    </tr>
    <tr>
      <th scope="row" style="text-align: right;">Full name:</th>
      <td style="text-align: left;">{{ employee.name }}
     {% if  employee.patronymic %}
          {{ employee.patronymic }}
    {% endif %}
          {{ employee.surname }}
      </td>
    </tr>
    <tr>
      <th scope="row" style="text-align: right;">Birth date:</th>
      <td style="text-align: left;">{{ employee.birth_date }}</td>
    </tr>
    <tr>
      <th scope="row" style="text-align: right;">Work time:</th>
      <td style="text-align: left;">
        {{ employee.started_work }} &mdash;
    {% if employee.ended_work %}
        {{ employee.ended_work }}
    {% else %}
        Now
    {% endif %}
      </td>
    </tr>
    <tr>
      <th scope="row" style="text-align: right;">Work place:</th>
      <td style="text-align: left;">    {{ employee.position }} in {{ employee.dept }}</td>
    </tr>
  </tbody>
</table>
{% endblock %}

eastwood/templates/employees/employee_dict.html
{% extends 'base.html' %}

{% block content %}
<h2>
  Dictionary
  {% if selected_key %}
  : {{ selected_key }}
   {% endif %}
</h2>
<ul class="list-group list-group-horizontal-xl">

{% for k, v in keys.items %}
  <li class="list-group-item"><a href="{{k}}">{{ v }}</a></li>
{% endfor %}
</ul>

{% if dict %}

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Full name</th>
      <th scope="col">Position and Department</th>
      <th scope="col">Worked time</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in object_list %}

      <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>
        <a href="{% url 'employees:detail' employee.id %}">
          {{ employee.name }}
           {% if  employee.patronymic %}
                {{ employee.patronymic }}
          {% endif %}
          {{ employee.surname }}
        </a>
      </td>
      <td>{{ employee.position }}, <a href="{% url 'employees:dept' employee.dept.id %}"> {{ employee.dept }}</a></td>
      <td>
        {{ employee.started_work }} &mdash;
        {% if employee.ended_work %}
            {{ employee.ended_work }}
        {% else %}
           now
        {% endif %}
      </td>
      </tr>

    {% endfor %}
  </tbody>
</table>

{% include 'pagination.html' %}

{% endif %}

{% endblock %}

eastwood/templates/employees/employee_list.html
{% extends 'base.html' %}

{% block content %}
<h2>Employees</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Full name</th>
      <th scope="col">Position and Department</th>
      <th scope="col">Worked time</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in object_list %}

      <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>
        <a href="{% url 'employees:detail' employee.id %}">
          {{ employee.name }}
           {% if  employee.patronymic %}
                {{ employee.patronymic }}
          {% endif %}
          {{ employee.surname }}
        </a>
      </td>
      <td>{{ employee.position }}, <a href="{% url 'employees:dept' employee.dept.id %}"> {{ employee.dept }}</a></td>
      <td>
        {{ employee.started_work }} &mdash;
        {% if employee.ended_work %}
            {{ employee.ended_work }}
        {% else %}
           now
        {% endif %}
      </td>
      </tr>

    {% endfor %}
  </tbody>
</table>

{% include 'pagination.html' %}

{% endblock %}

eastwood/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h2>Home page</h2>

{% endblock %}

eastwood/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container justify-content-center">
    <ul class="nav">
      <li class="nav-item">
         <a class="nav-link" href="{%url 'core:home'%}">Home</a>
      </li>
      <li class="nav-item">
         <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Employees list
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'employees:list' %}">Default list</a>
          <a class="dropdown-item" href="{% url 'employees:actual' %}">Recent employees</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'employees:dict' %}">Dictionary</a>
      </li>
    </ul>
  </div>
</nav>

eastwood/templates/pagination.html
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page=1">1</a>
        </li>
    {% endif %}

        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
        </li>

    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
    {% endif %}
</ul>